name: 'VAX Generator'
description: 'Generates SBOM & VAX for the Repository and persist it in GCP Bucket'
inputs :
  gcs_credentials : # gcp creds
    description: 'gcp creds'
    required: true
  repo-token : # Repo access Token
    description: 'Token to access Repo'
    required: true
  owner : # Owner Name of the repository
    description: 'Repository Owner Name'
    required: true
  repoName : # Target Repo
    description: 'Name of the Repo to be scanned'
    required: true
  path : # Target file path
    description: 'Path of the Repo to be scanned'
    required: true  
runs:
  using: 'node16'
  main: 'dist/index.js'

