name: 'SBOM Generation'
description: 'Greet someone and record the time'
inputs :
  gcs_credentials : # gcp creds 
    description: 'gcp creds'
    required: true
  repo-token : # Repo access Token
    description: 'Token to access Repo'
    required: true
  owner : # Owner Name of the repository
    description: 'Repository Owner Name'
    required: true
  repoName : # Target Repo 
    description: 'Name of the Repo to be scanned'
    required: true  
runs:
  using: 'node16'
  main: 'dist/index.js'

